---
   - name: Install XFCE4
     apt: name=xfce4 state=present update_cache=yes
    
   - name: Modify XWrapper
     lineinfile: dest=/etc/X11/Xwrapper.config regexp='^allowed_users=' line='allowed_users=anybody'
